allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    def subprojectDir = project.projectDir.canonicalPath
    def rootDir = rootProject.projectDir.canonicalPath
    if (subprojectDir.substring(0, 2).equalsIgnoreCase(rootDir.substring(0, 2))) {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete(rootProject.buildDir)
}
